redoing branch to prune bad git commit
Alvearie/de-identification pull request #45
Opened 2021-02-12 20:36 UTC by CZwarts

2021-02-12 22:40 UTC, DenisRicard approved these changes
Good. Let's use better commit messages next time though ;-)

2021-02-13 00:04 UTC, jarrettranderson requested changes

2021-02-13 00:04 UTC, jarrettranderson commented on ipv-core/src/main/java/com/ibm/whc/deid/util/ContinentManager.java
> +  protected transient volatile Map<String, List<Location>> continentListMap;
We could look at making Location Serializable and we could define the Map and List as actual types if that is impacting the scans.

2021-02-13 00:04 UTC, jarrettranderson commented on ipv-core/src/main/java/com/ibm/whc/deid/util/CountryManager.java
> +  protected transient final Resources resourceType = Resource.COUNTRY;
All the implementations of Resources are enums, so they are Serializable - probably just a matter of declaring Resources interface to be serializable.

2021-03-29 14:27 UTC, closed without merging